// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
/* tslint:disable */
let _VERSION = '0.0.1-SNAPSHOT'; // This value will be overwritten by Webpack
let _DEBUG_INFO_ENABLED = false; // This value will be overwritten by Webpack
let _SERVER_API_URL = ''; // This value will be overwritten by Webpack
let _ACTIVITI_API_URL = 'http://localhost:8082';
let _UPLOAD_URL = '/riskapp/api/fileUpload';
let _FASTDFS_API_URL='http://22.144.101.75:8888/';
let _WEBOFFICE_API_URL = 'http://22.144.104.163:8011/web-apps/';
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
/* @toreplace SERVER_API_URL */
/* tslint:enable */
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;
export const SERVER_API_URL = _SERVER_API_URL;
export const ACTIVITI_API_URL = _ACTIVITI_API_URL;
export let UPLOAD_URL = _UPLOAD_URL;
export const WEBOFFICE_API_URL = _WEBOFFICE_API_URL;
export const FASTDFS_API_URL = _FASTDFS_API_URL;
